apiVersion: v1
kind: Service
metadata:
  labels:
    app: coworking-project
  name: coworking-project
spec:
  ports:
  - port: 5153
    protocol: TCP
    targetPort: 5153
  selector:
    app: coworking-project
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking


        image: 799139823639.dkr.ecr.us-east-1.amazonaws.com/myecr:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_HOST
          value: postgresql-86944b65cb-7k7b5
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: myuser
        - name: DB_PASSWORD
          value: mypassword
        - name: DB_NAME
          value: mydatabase
      restartPolicy: Always